sonar.projectKey=contactvault-backend
sonar.projectName=ContactVault Backend

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=\
  src/main/java/**/dto/**, \
  src/main/java/**/entity/**, \
  src/main/java/**/mapper/**, \
  src/main/java/**/exception/Bad*.java, \
  src/main/java/**/exception/Forbidden*.java, \
  src/main/java/**/exception/NotFound*.java, \
  src/main/java/**/exception/Unauthorized*.java

sonar.coverage.exclusions=\
  src/main/java/**/dto/**, \
  src/main/java/**/entity/**, \
  src/main/java/**/mapper/**, \
  src/main/java/**/config/**, \
  src/main/java/**/exception/**