sonar.projectKey=contactvault-frontend
sonar.projectName=ContactVault Frontend

sonar.sources=src
sonar.exclusions=\
  node_modules/**, \
  dist/**, \
  src/components/ui/**, \
  src/routeTree.gen.ts

sonar.coverage.exclusions=\
  src/components/ui/**, \
  src/routeTree.gen.ts, \
  src/main.tsx, \
  src/types/**, \
  src/lib/queryKeys.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json