spring:
  application:
    name: contactvault
  profiles:
    active: dev

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
  jwt:
    accessTokenExpirationMillis: 86400000 # 24 Hours
    secret: quNgoHI1I8brjahgO9AdYdHmHXBIuoo8cYdltHdr3mV
