spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contactvault?createDatabaseIfNotExist=true
    username: root
    password: hash,174

  jpa:
    show-sql: true

frontEndUrl: http://localhost:3000